describe("Chinese remainder theorem", function()
	local crt = require("math.chinese_remainder_theorem")

	it("should handle cases with solution", function()
		assert.equal(0, crt({ { 0, 3 } }))
		assert.equal(65, crt({ { 1, 8 }, { 2, 9 } }))
		assert.equal(1, crt({ { 1, 54 }, { 1, 73 }, { 1, 997 }, { 1, 102353 } }))
		assert.equal(39, crt({ { 0, 3 }, { 3, 4 }, { 4, 5 } }))
		assert.equal(23, crt({ { 2, 3 }, { 3, 5 }, { 2, 7 } }))
		assert.equal(34, crt({ { 1, 3 }, { 4, 5 }, { 6, 7 } }))
		assert.equal(388, crt({ { 3, 7 }, { 3, 5 }, { 4, 12 } }))
		assert.equal(87, crt({ { 2, 5 }, { 3, 7 }, { 10, 11 } }))
		assert.equal(29, crt({ { 2, 3 }, { 1, 4 }, { 7, 11 } }))
		assert.equal(125, crt({ { 6, 7 }, { 8, 9 }, { 4, 11 }, { 8, 13 } }))
		assert.equal(89469, crt({ { 6, 11 }, { 13, 16 }, { 9, 21 }, { 19, 25 } }))
	end)

	it("should handle cases without solution", function()
		assert.equal(nil, crt({ { 5, 17 }, { 4, 17 } }))
		assert.equal(nil, crt({ { 3, 4 }, { 0, 6 } }))
		assert.equal(nil, crt({ { 3, 13 }, { 7, 1 } }))
	end)

	it("should throw error when some of the moduli is zero", function()
		assert.has_error(function()
			crt({ { 0, 0 } })
		end)
	end)

	it("should throw error when some of the moduli is negative", function()
		assert.has_error(function()
			crt({ { 0, -1 } })
		end)
	end)
end)
