describe("Factorial", function()
	local factorial = require("math.factorial")
	it("works", function()
		assert.equal(1, factorial(0))
		assert.equal(1, factorial(1))
		assert.equal(6, factorial(3))
		assert.equal(720, factorial(6))
		assert.equal(3628800, factorial(10))
		assert.equal(math.huge, factorial(1000))
	end)
end)
