describe("Fraction", function()
	local fraction = require("math.fraction")
	local frac = fraction.new
	it("can be constructed", function()
		assert.same({ numerator = 0, denominator = 1 }, frac(0, 100))
		assert.same({ numerator = 33, denominator = 41 }, frac(33, 41))
	end)
	it("is shortened", function()
		assert.same({ numerator = 3, denominator = 41 * 7 }, frac(33, 41 * 77))
	end)
	it("always has the sign in the numerator", function()
		assert.same({ numerator = -1, denominator = 1 }, frac(-1, 1))
		assert.same({ numerator = -1, denominator = 1 }, frac(1, -1))
		assert.same({ numerator = 1, denominator = 1 }, frac(-1, -1))
		assert.same({ numerator = 1, denominator = 1 }, frac(1, 1))
	end)
	it("can be created from decimals", function()
		for n = 1, 100 do
			assert.same(frac(1, 2 ^ n), fraction.from_number(2 ^ -n))
		end
		-- Test using random mantissas; this has to be more limited
		-- as Lua 5.1 uses ints for its random
		for n = 1, 30 do
			local mantissa = math.random(1, 2 ^ n)
			assert.same(fraction.new(mantissa, 2 ^ n), fraction.from_number(mantissa * 2 ^ -n))
		end
		assert.same(frac(1, 3), fraction.from_number(1 / 3))
		-- TODO assert.same(fraction.new(3, 10), fraction.from_number(0.3))
	end)
	describe("arithmetic", function()
		it("minus", function()
			assert.same(frac(1, 2), -frac(1, -2))
			assert.same(frac(-1, 2), -frac(1, 2))
		end)
		it("addition", function()
			assert.same(frac(4, 15), frac(1, 5) + frac(1, 15))
			assert.same(frac(1, 2), frac(-1, 2) + 1)
		end)
		it("subtraction", function()
			assert.same(frac(2, 15), frac(1, 5) - frac(1, 15))
			assert.same(frac(-1, 2), frac(1, 2) - 1)
		end)
		it("multiplication", function()
			assert.same(frac(11 * 7, 3 * 5), frac(11, 3) * frac(7, 5))
			assert.same(frac(1, 1), frac(1, 2) * 2)
		end)
		it("modulo", function()
			assert.same(frac(55 % 21, 15), frac(11, 3) % frac(7, 5))
			assert.same(frac(1, 1), 3 % frac(2, 1))
		end)
		it("integer exponentiation", function()
			assert.same(frac(-100, 1), frac(-1, 100) ^ -1)
			assert.same(frac(2 ^ 100, 1), frac(2, 1) ^ 100)
		end)
	end)
	describe("comparison", function()
		local function srand(to) -- signed, nonzero random
			if math.random() < 0.5 then
				return -math.random(to)
			end
			return math.random(to)
		end
		for _ = 1, 1e3 do
			local a, b = frac(srand(1e3), srand(1e3)), frac(srand(1e3), srand(1e3))
			local a_num, b_num = a:to_number(), b:to_number()
			assert.truthy(a == a)
			assert.truthy(b == b)
			assert.equal(a_num == b_num, a == b)
			assert.equal(a_num < b_num, a < b)
			assert.equal(a_num > b_num, a > b)
			assert.equal(a_num <= b_num, a <= b)
			assert.equal(a_num >= b_num, a >= b)
		end
	end)
	it("string conversion works", function()
		assert.same(tostring(frac(-12, 11)), -12 .. "/" .. 11)
		assert.same(tostring(frac(-12, -11)), 12 .. "/" .. 11)
	end)
end)
