describe("max", function()
	local max = require("math.max")
	it("rejects 0 values", function()
		assert.has_error(function()
			return max()
		end)
	end)
	it("returns 1 value", function()
		assert.equal(42, max(42))
	end)
	it("returns the max of 2 or more values", function()
		assert.equal(101, max(42, 101))
		assert.equal(101, max(33, 101, -42, 42, 3, 0))
		local frac = require("math.fraction").new
		assert.equal(frac(3, 4), max(frac(-1, 2), frac(3, 4), frac(1, 4)))
	end)
end)
