describe("min", function()
	local min = require("math.min")
	it("rejects 0 values", function()
		assert.has_error(function()
			return min()
		end)
	end)
	it("returns 1 value", function()
		assert.equal(42, min(42))
	end)
	it("returns the min of 2 or more values", function()
		assert.equal(42, min(42, 101))
		assert.equal(-42, min(33, 101, -42, 42, 3, 0))
		local frac = require("math.fraction").new
		assert.equal(frac(-1, 2), min(frac(-1, 2), frac(3, 4), frac(1, 4)))
	end)
end)
